services:
  - type: web
    name: civiclink-backend
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --workers 2
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SECRET
        sync: false
      - key: SUPABASE_BUCKET_NAME
        value: product_image
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: DEBUG
        value: "False"
      - key: YOLO_MODEL_PATH
        value: models/pothole_yolov8_best.pt
      - key: MIN_CONFIDENCE
        value: "0.1"